# =====================================================================
# JumpCloud Device Enrollment - bootstrap command (zip deployment)
# Generated by build\New-DeploymentScript.ps1 - DO NOT EDIT BY HAND.
#
# JumpCloud console setup:
#   - Command type: PowerShell, Run As: root
#   - Timeout: at least 3900 seconds
#   - no attachment needed: the zip is downloaded from $ZipUrl
#     (JumpCloud places attached files in C:\Windows\Temp\ on Windows)
#   - the Apikey / device.id template variables are substituted at
#     dispatch, quotes included: the BARE assignments below are
#     intentional and nothing else may share those lines
#
# Alternatively set $ZipUrl to an HTTPS location hosting the zip.
# =====================================================================
$ApiKey   = {{Apikey}}
$SystemId = {{device.id}}
$ZipUrl   = 'https://raw.githubusercontent.com/rahultestingjc/jumpcl' +
    'oud-enrollment-deploy/main/JumpCloudEnrollment.zip'

# ================= TENANT SETTINGS - EDIT THESE =================
# Everything an organization changes lives HERE, not in the package.
$OrgId          = 'YOUR_JUMPCLOUD_ORG_ID'   # required (console: Settings)
$Region         = 'US'                      # US or EU tenant
$CompanyName    = 'Your Organization'
$SupportContact = 'your IT administrator'
$AccentColor    = '#0E8A5F'                 # brand color (hex)
$LogoPath       = ''                        # optional logo PNG on device
$DeferMinutes   = 120                       # Remind Me Later snooze
$LdapServer     = 'ldap.jumpcloud.com'      # rarely changed
$LdapPort       = 636                       # 636 = LDAPS, 389 = StartTLS
# ================================================================

# Outside a JumpCloud command the variables stay unsubstituted and the
# bare assignments parse as scriptblocks - refuse to continue.
if ($ApiKey -isnot [string] -or $SystemId -isnot [string]) {
    Write-Host 'Status: RequiresAction | Issue: run via a JumpCloud command'
    exit 1
}
$ApiKey   = $ApiKey.Trim().Trim("'").Trim('"')
$SystemId = $SystemId.Trim().Trim("'").Trim('"')

# Pinned SHA-256 of JumpCloudEnrollment.zip (set by the build). A zip
# downloaded from $ZipUrl MUST match it - endpoints run this as SYSTEM.
$ZipSha256 = 'DF94B184B93E8812294A0E386B6050BDD2A73BDC5DB5E109106416F3C549A330'

Set-ExecutionPolicy -Scope Process Bypass -Force
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$zipName = 'JumpCloudEnrollment.zip'
$zip = $null
if (-not [string]::IsNullOrWhiteSpace($ZipUrl)) {
    # URL mode: always fetch fresh, then verify against the pinned hash.
    $zip = Join-Path 'C:\Windows\Temp' $zipName
    try {
        Invoke-WebRequest -Uri $ZipUrl -OutFile $zip -UseBasicParsing `
            -ErrorAction Stop
    }
    catch {
        Write-Host 'Status: RequiresAction | Issue: Zip download failed'
        Write-Host "Detail: $($_.Exception.Message)"
        exit 1
    }
    $actual = (Get-FileHash -Path $zip -Algorithm SHA256).Hash
    if ($actual -ne $ZipSha256) {
        Remove-Item $zip -Force -ErrorAction SilentlyContinue
        Write-Host 'Status: RequiresAction | Issue: Zip hash mismatch'
        Write-Host "Expected $ZipSha256 got $actual"
        exit 1
    }
    Write-Host 'Package hash verified.'
}
else {
    # Attachment mode: use the zip JumpCloud placed on the device.
    $candidates = @(
        (Join-Path (Get-Location).Path $zipName),
        (Join-Path 'C:\Windows\Temp' $zipName),
        (Join-Path $env:TEMP $zipName)
    )
    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { $zip = $candidate; break }
    }
    if (-not $zip) {
        Write-Host "Status: RequiresAction | Issue: $zipName not found"
        Write-Host "Searched: $($candidates -join '; ')"
        exit 1
    }
}
Write-Host "Using package: $zip"

$appDir = 'C:\ProgramData\JumpCloudEnrollment\app'
try {
    if (Test-Path $appDir) {
        Remove-Item -Path $appDir -Recurse -Force -ErrorAction Stop
    }
}
catch {
    Write-Host 'Warning: could not fully clear app dir - overwriting.'
}
New-Item -ItemType Directory -Path $appDir -Force | Out-Null
try {
    Expand-Archive -Path $zip -DestinationPath $appDir -Force -ErrorAction Stop
}
catch {
    # Fallback for hosts where Microsoft.PowerShell.Archive misbehaves.
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $appDir)
}

$entry = Join-Path $appDir 'Invoke-JumpCloudEnrollment.ps1'
if (-not (Test-Path $entry)) {
    Write-Host 'Status: RequiresAction | Issue: entry script missing'
    exit 1
}

# In-process invocation: the API key stays inside this PowerShell process
# and never appears on any OS command line. Tenant settings flow through
# as parameters and override the packaged defaults.
& $entry -ApiKey $ApiKey -SystemId $SystemId -OrgId $OrgId `
    -Region $Region -CompanyName $CompanyName `
    -SupportContact $SupportContact -AccentColor $AccentColor `
    -LogoPath $LogoPath -DeferMinutes $DeferMinutes `
    -LdapServer $LdapServer -LdapPort $LdapPort
