# =====================================================================
# JumpCloud Device Enrollment - bootstrap command (zip deployment)
# Generated by build\New-DeploymentScript.ps1 - DO NOT EDIT BY HAND.
#
# JumpCloud console setup:
#   - Command type: PowerShell, Run As: root
#   - Timeout: at least 3900 seconds
#   - no attachment needed: the zip is downloaded from $ZipUrl
#     (JumpCloud places attached files in C:\Windows\Temp\ on Windows)
#   - the Apikey / device.id template variables are substituted at
#     dispatch, quotes included: the BARE assignments below are
#     intentional and nothing else may share those lines
#
# Alternatively set $ZipUrl to an HTTPS location hosting the zip.
# Either way the zip must match the SHA-256 pinned below, and everything
# this command puts on the device is deleted when it finishes.
# =====================================================================
$ApiKey   = {{Apikey}}
$SystemId = {{device.id}}
$ZipUrl   = 'https://raw.githubusercontent.com/rahultestingjc/jumpcl' +
    'oud-enrollment-deploy/main/JumpCloudEnrollment.zip'

# ================= TENANT SETTINGS - EDIT THESE =================
# Everything an organization changes lives HERE, not in the package.
$OrgId          = 'YOUR_JUMPCLOUD_ORG_ID'   # required (console: Settings)
$Region         = 'US'                      # US or EU tenant
$CompanyName    = 'Your Organization'
$SupportContact = 'your IT administrator'
$AccentColor    = '#0E8A5F'                 # brand color (hex)
$LogoPath       = ''                        # optional logo PNG on device
$LdapServer     = 'ldap.jumpcloud.com'      # rarely changed
$LdapPort       = 636                       # 636 = LDAPS, 389 = StartTLS
$KeepLogs       = $false                    # $true keeps logs (debugging)
# ================================================================

# Outside a JumpCloud command the variables stay unsubstituted and the
# bare assignments parse as scriptblocks - refuse to continue.
if ($ApiKey -isnot [string] -or $SystemId -isnot [string]) {
    Write-Host 'Status: RequiresAction | Issue: run via a JumpCloud command'
    exit 1
}
$ApiKey   = $ApiKey.Trim().Trim("'").Trim('"')
$SystemId = $SystemId.Trim().Trim("'").Trim('"')

# Pinned SHA-256 of JumpCloudEnrollment.zip (set by the build). A zip
# downloaded from $ZipUrl MUST match it - endpoints run this as SYSTEM.
$ZipSha256 = '53DBCDD06D1DF21D5977B49CFC7347C553DFC33B7152AA6269D77E0CC683D982'

Set-ExecutionPolicy -Scope Process Bypass -Force
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Private working folder with a random name. CreateDirectory applies the
# permissions (SYSTEM + Administrators only) at creation, so no other
# user can ever open it, plant files in it, or swap the package inside.
$sidType = [System.Security.Principal.SecurityIdentifier]
$inheritType = [System.Security.AccessControl.InheritanceFlags]
$inherit = $inheritType::ContainerInherit -bor $inheritType::ObjectInherit
$workAcl = New-Object System.Security.AccessControl.DirectorySecurity
$workAcl.SetAccessRuleProtection($true, $false)
foreach ($sidText in @('S-1-5-18', 'S-1-5-32-544')) {
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        (New-Object $sidType($sidText)), 'FullControl', $inherit, 'None', 'Allow')
    $workAcl.AddAccessRule($rule)
}
$workName = 'Temp\JCEnroll-' + [guid]::NewGuid().ToString('N')
$work = Join-Path $env:windir $workName
try { [void][System.IO.Directory]::CreateDirectory($work, $workAcl) }
catch {
    Write-Host 'Status: RequiresAction | Issue: Could not create working folder'
    exit 1
}

$zipName = 'JumpCloudEnrollment.zip'
$zip = Join-Path $work 'package.zip'
$sourceZip = $null
$exitCode = 1
try {
    if (-not [string]::IsNullOrWhiteSpace($ZipUrl)) {
        # URL mode: download straight into the private folder.
        try {
            Invoke-WebRequest -Uri $ZipUrl -OutFile $zip -UseBasicParsing `
                -ErrorAction Stop
        }
        catch {
            Write-Host 'Status: RequiresAction | Issue: Zip download failed'
            Write-Host "Detail: $($_.Exception.Message)"
            exit 1
        }
    }
    else {
        # Attachment mode: copy the zip JumpCloud placed on the device.
        $candidates = @(
            (Join-Path (Get-Location).Path $zipName),
            (Join-Path $env:windir "Temp\$zipName"),
            (Join-Path $env:TEMP $zipName)
        )
        foreach ($candidate in $candidates) {
            if (Test-Path -LiteralPath $candidate) { $sourceZip = $candidate; break }
        }
        if (-not $sourceZip) {
            Write-Host "Status: RequiresAction | Issue: $zipName not found"
            Write-Host "Searched: $($candidates -join '; ')"
            exit 1
        }
        Copy-Item -LiteralPath $sourceZip -Destination $zip -Force
        Write-Host "Using package: $sourceZip"
    }

    # Hash the private copy: the bytes checked are the bytes that run.
    $actual = (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash
    if ($actual -ne $ZipSha256) {
        Write-Host 'Status: RequiresAction | Issue: Zip hash mismatch'
        Write-Host "Expected $ZipSha256 got $actual"
        exit 1
    }
    Write-Host 'Package hash verified.'

    $appDir = Join-Path $work 'app'
    try {
        Expand-Archive -LiteralPath $zip -DestinationPath $appDir -Force `
            -ErrorAction Stop
    }
    catch {
        # Fallback for hosts where Microsoft.PowerShell.Archive misbehaves.
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $appDir)
    }

    $entry = Join-Path $appDir 'Invoke-JumpCloudEnrollment.ps1'
    if (-not (Test-Path -LiteralPath $entry)) {
        Write-Host 'Status: RequiresAction | Issue: entry script missing'
        exit 1
    }

    # In-process invocation: the API key stays inside this PowerShell
    # process and never appears on any OS command line. Tenant settings
    # flow through as parameters and override the packaged defaults.
    & $entry -ApiKey $ApiKey -SystemId $SystemId -OrgId $OrgId `
        -Region $Region -CompanyName $CompanyName `
        -SupportContact $SupportContact -AccentColor $AccentColor `
        -LogoPath $LogoPath -KeepLogs:$KeepLogs `
        -LdapServer $LdapServer -LdapPort $LdapPort
    $exitCode = $LASTEXITCODE
}
finally {
    # Self-destruct. cmd's rmdir removes links without following them.
    & cmd.exe /d /c rmdir /s /q $work 2>$null | Out-Null
    if ($sourceZip) {
        Remove-Item -LiteralPath $sourceZip -Force -ErrorAction SilentlyContinue
    }
    # Backstop: the enrollment script already cleared its staging folder.
    if (-not $KeepLogs) {
        $stagingRoot = 'C:\ProgramData\JumpCloudEnrollment'
        & cmd.exe /d /c rmdir /s /q $stagingRoot 2>$null | Out-Null
    }
}
exit $exitCode
